// Generated by `npm run types` from schemas/; do not edit.

/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Part".
 */
export type Part =
  | {
      /**
       * What each end is welded or joined to.
       */
      from: string;
      /**
       * Hangers, mm from this straight's start.
       */
      hangers_mm: number[];
      id: string;
      kind: "straight";
      length_mm: number;
      to: string;
    }
  | {
      angle_deg: number;
      clr_mm: number;
      /**
       * Hangers, mm of arc from this bend's start.
       */
      hangers_mm: number[];
      id: string;
      kind: "bend";
      /**
       * From the previous bend's plane; absent for a route's first bend.
       */
      rotation_deg?: number | null;
      /**
       * Used whole: no cut.
       */
      stock_as_is: boolean;
      /**
       * Stock bend it is cut from, degrees.
       */
      stock_deg: number;
      /**
       * Direction the tube turns toward (first bend's placement), unit vector.
       *
       * @minItems 3
       * @maxItems 3
       */
      turns_toward: [number, number, number];
    }
  | {
      from: string;
      id: string;
      kind: "branch";
      length_mm: number;
      /**
       * The main pipe the cope fits, and the angle from its flow direction to the branch.
       */
      main_od_mm: number;
      saddle_mm: number;
      tee_angle_deg: number;
      to: string;
    };
/**
 * How two parts are joined.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Joint".
 */
export type Joint = "butt" | "slip" | "v_band" | "flange";
/**
 * A piece of centreline starting `s0_mm` along its route.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PieceLayout".
 */
export type PieceLayout =
  | {
      /**
       * @minItems 3
       * @maxItems 3
       */
      from: [number, number, number];
      kind: "straight";
      s0_mm: number;
      /**
       * @minItems 3
       * @maxItems 3
       */
      to: [number, number, number];
    }
  | {
      angle_deg: number;
      /**
       * @minItems 3
       * @maxItems 3
       */
      centre: [number, number, number];
      /**
       * @minItems 3
       * @maxItems 3
       */
      from: [number, number, number];
      kind: "arc";
      radius_mm: number;
      s0_mm: number;
      /**
       * @minItems 3
       * @maxItems 3
       */
      to: [number, number, number];
    };
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "ParamKind".
 */
export type ParamKind = "number" | "material" | "direction" | "offsets";
/**
 * Where the in-cylinder state at EVO came from.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "EvoSource".
 */
export type EvoSource =
  | {
      kind: "estimated";
      map_kpa: number;
    }
  | {
      kind: "given";
    };
/**
 * Which solver produced a result.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "SolverKind".
 */
export type SolverKind = "time_domain" | "four_pole";
/**
 * TVD slope limiter for MUSCL reconstruction of primitive variables.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Limiter".
 */
export type Limiter = "minmod" | "van_leer" | "van_leer_tvb";
/**
 * Where a value comes from, in order of precedence.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Provenance2".
 */
export type Provenance2 = "measured" | "published" | "derived" | "estimated";
/**
 * How far a value may be from the truth.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Uncertainty".
 */
export type Uncertainty =
  | {
      high: number;
      kind: "range";
      low: number;
    }
  | {
      fraction: number;
      kind: "relative";
    }
  | {
      kind: "absolute";
      plus_minus: number;
    }
  | {
      factor: number;
      kind: "factor";
    };
/**
 * Who hears the scene. Positions are in the vehicle frame (X forward, Y left, Z up, origin at
 * the downpipe flange), mm.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Listener".
 */
export type Listener =
  | {
      kind: "receiver";
    }
  | {
      ear_spacing_mm: number;
      kind: "stereo";
      turn_deg: number;
    }
  | {
      kind: "points";
      positions_mm: [number, number, number][];
    }
  | {
      kind: "pass_by";
      /**
       * @minItems 3
       * @maxItems 3
       */
      mic_mm: [number, number, number];
      speed_kmh: [number, number][];
      start_mm: number;
    }
  | {
      kind: "cabin";
    };
/**
 * A render in progress.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "RenderProgress".
 */
export type RenderProgress =
  | {
      cycle: number;
      residual?: number | null;
      stage: "settle";
    }
  | {
      fraction: number;
      stage: "march";
    };
/**
 * A point either solved or failed; failures carry the reason and no numbers.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PointOutcome".
 */
export type PointOutcome =
  | (PointResult & {
      status: "solved";
    })
  | {
      error: string;
      rpm: number;
      status: "failed";
    };

/**
 * The app backend's replies, for generating the frontend's types.
 */
export interface Api {
  clearance: Clearance;
  differences: OrderDifference[];
  fabrication: Package;
  layout: Layout;
  manifests: Manifest[];
  /**
   * One operating point as a time-domain sweep streams it.
   */
  point:
    | (PointResult & {
        status: "solved";
      })
    | {
        error: string;
        rpm: number;
        status: "failed";
      };
  progress: CycleProgress;
  recording_check: RecordingComparison;
  render: RenderInfo;
  render_progress: RenderProgress;
  scene: Scene;
  sensitivity: Sensitivity;
  sweep: SweepResult;
  tracks: OrderTracks;
  tuning: Tuning;
  verification: CaseReport[];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Clearance".
 */
export interface Clearance {
  /**
   * Stretches closer than the gap wanted there.
   */
  contacts: Contact[];
  placement: Placement;
  /**
   * Closest approach of each route.
   */
  routes: RouteClearance[];
}
/**
 * A stretch of pipe closer to the underbody than wanted.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Contact".
 */
export interface Contact {
  /**
   * Where it is closest, on the centreline and on the scan.
   *
   * @minItems 3
   * @maxItems 3
   */
  at: [number, number, number];
  /**
   * Along the centreline from the route's start, mm.
   */
  from_mm: number;
  min_mm: number;
  route: string;
  /**
   * @minItems 3
   * @maxItems 3
   */
  scan_point: [number, number, number];
  to_mm: number;
  wanted_mm: number;
  /**
   * The clearance zone that set the gap, if one did.
   */
  zone?: string | null;
}
/**
 * Rigid transform `x ↦ R x + t`.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Placement".
 */
export interface Placement {
  /**
   * RMS distance between the reference points as placed and as given, mm.
   */
  residual_mm: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  rotation: [[number, number, number], [number, number, number], [number, number, number]];
  /**
   * @minItems 3
   * @maxItems 3
   */
  translation: [number, number, number];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "RouteClearance".
 */
export interface RouteClearance {
  /**
   * @minItems 3
   * @maxItems 3
   */
  at: [number, number, number];
  at_mm: number;
  min_mm: number;
  route: string;
}
/**
 * An engine order of two solved configurations, `b − a`.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "OrderDifference".
 */
export interface OrderDifference {
  /**
   * Mean level difference over the cruise band, at speeds both solved, dB.
   */
  cruise_db?: number | null;
  /**
   * The largest difference either way over the sweep, `[rpm, dB]`.
   *
   * @minItems 2
   * @maxItems 2
   */
  largest?: [number, number] | null;
  order: number;
  /**
   * Highest level over the sweep, of `a` and of `b`, dB.
   *
   * @minItems 2
   * @maxItems 2
   */
  peak_db: [number | null, number | null];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Package".
 */
export interface Package {
  routes: RouteParts[];
  /**
   * Straights nested into stock lengths.
   */
  sticks: Stick[];
  warnings: string[];
  welds: Weld[];
}
/**
 * The parts of a route, or of an element's own tube (`stub/tube`, `helmholtz/neck`,
 * `helmholtz/can`), from its start.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "RouteParts".
 */
export interface RouteParts {
  /**
   * @minItems 3
   * @maxItems 3
   */
  end: [number, number, number];
  /**
   * Centreline length.
   */
  length_mm: number;
  material: string;
  od_mm: number;
  parts: Part[];
  route: string;
  /**
   * @minItems 3
   * @maxItems 3
   */
  start: [number, number, number];
  /**
   * Flow direction at the start.
   *
   * @minItems 3
   * @maxItems 3
   */
  start_direction: [number, number, number];
  wall_mm: number;
}
/**
 * One stock length of tube and the straights cut from it.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Stick".
 */
export interface Stick {
  cuts: string[];
  material: string;
  od_mm: number;
  offcut_mm: number;
  used_mm: number;
  wall_mm: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Weld".
 */
export interface Weld {
  /**
   * @minItems 3
   * @maxItems 3
   */
  at: [number, number, number];
  /**
   * The two things joined (part ids or `element.port`).
   *
   * @minItems 2
   * @maxItems 2
   */
  between: [string, string];
  id: string;
  joint: Joint;
  /**
   * Filler or method needed for the metals meeting here.
   */
  note?: string | null;
  route: string;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Layout".
 */
export interface Layout {
  elements: ElementLayout[];
  routes: RouteLayout[];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "ElementLayout".
 */
export interface ElementLayout {
  /**
   * Outer envelope as coaxial frustums (cones and cylinders).
   */
  body: Frustum[];
  id: string;
  ports: PortLayout[];
  type: string;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Frustum".
 */
export interface Frustum {
  d_from_mm: number;
  d_to_mm: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  from: [number, number, number];
  /**
   * @minItems 3
   * @maxItems 3
   */
  to: [number, number, number];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PortLayout".
 */
export interface PortLayout {
  name: string;
  /**
   * @minItems 3
   * @maxItems 3
   */
  position: [number, number, number];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "RouteLayout".
 */
export interface RouteLayout {
  /**
   * Centreline radius of the bend at each via point.
   */
  bend_radius_mm: number[];
  /**
   * Hanger positions on the centreline.
   */
  hangers: [number, number, number][];
  id: string;
  /**
   * Centreline length: the flow solver's x-axis along this route.
   */
  length_mm: number;
  material: string;
  od_mm: number;
  pieces: PieceLayout[];
  /**
   * Start port, via points, end port.
   */
  points: [number, number, number][];
  wall_mm: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Manifest".
 */
export interface Manifest {
  name: string;
  param?: Param[];
  /**
   * Fixed ports; a chamber adds `out2`, `out3`, … for its extra outlets.
   */
  ports: string[];
  summary: string;
  /**
   * Element type, as in the project file.
   */
  type: string;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Param".
 */
export interface Param {
  default?: number | null;
  /**
   * Field name in the project file.
   */
  key: string;
  kind: ParamKind;
  label: string;
  max?: number | null;
  min?: number | null;
  /**
   * Numbers only: unit, inclusive range, and the editor's default.
   */
  unit?: string | null;
}
/**
 * Solution at one engine speed.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PointResult".
 */
export interface PointResult {
  /**
   * Mean static pressure above ambient at the downpipe flange, Pa (time domain only).
   */
  backpressure_pa?: number | null;
  /**
   * |outlet mass − source mass| / source mass over the analysed cycles (time domain only).
   */
  mass_balance_error?: number | null;
  mass_flow_kg_s: number;
  /**
   * Engine orders 1–8: `(order, frequency_hz, spl_db)`.
   */
  orders: [number, number, number][];
  /**
   * Mean gas temperature leaving the reference outlet, K.
   */
  outlet_temperature_k: number;
  overall_db: number;
  overall_dba: number;
  provenance: Provenance;
  rpm: number;
  spectrum: Line[];
  turbine_power_w: number;
}
/**
 * How a result was produced; attached to every result.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Provenance".
 */
export interface Provenance {
  cells: number;
  core_version: string;
  dx_max_mm: number;
  dx_min_mm: number;
  dx_target_mm: number;
  evo: EvoState;
  evo_source: EvoSource;
  gas_table: string;
  project_hash: string;
  /**
   * Four-pole result of a network with elements that are nonlinear at exhaust amplitudes
   * (valves, orifices): valid for small signals only.
   */
  small_signal: boolean;
  solver: SolverKind;
  /**
   * Wall and gas temperature model, with a BLAKE3 hash of its inputs.
   */
  thermal_profile: string;
  /**
   * Time-domain run details; absent for four-pole results.
   */
  time_domain?: TimeDomainRun | null;
  /**
   * Modelling limitations that affect this result.
   */
  warnings: string[];
}
/**
 * In-cylinder state at exhaust valve opening.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "EvoState".
 */
export interface EvoState {
  /**
   * Pa.
   */
  pressure_pa: number;
  /**
   * K.
   */
  temperature_k: number;
}
/**
 * Scheme and convergence of a time-domain run.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "TimeDomainRun".
 */
export interface TimeDomainRun {
  cfl: number;
  cfl_max: number;
  converged: boolean;
  cycles: number;
  limiter: Limiter;
  /**
   * Period of the solution in engine cycles (1 or 2).
   */
  period_cycles: number;
  /**
   * Largest relative change of the monitored signals between the last cycle and the cycle
   * one period earlier.
   */
  periodicity_residual: number;
  periodicity_tolerance: number;
}
/**
 * One spectral line at the receiver.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Line".
 */
export interface Line {
  frequency_hz: number;
  /**
   * Engine order (multiples of ½ for a four-stroke).
   */
  order: number;
  /**
   * Phase of the receiver pressure, rad (`e^{jωt}`, t = 0 at cylinder 1 firing TDC).
   */
  phase_rad: number;
  spl_db: number;
  spl_dba: number;
}
/**
 * A time-domain point in progress: engine cycles run, and how far the last differs from the
 * one before (the periodicity residual; `None` after the first).
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "CycleProgress".
 */
export interface CycleProgress {
  cycle: number;
  residual?: number | null;
  rpm: number;
}
/**
 * A window of a calibrated recording set against a render of the same engine speed at the
 * same place. Recordings validate; nothing here is fed back into an input.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "RecordingComparison".
 */
export interface RecordingComparison {
  bands: BandComparison[];
  /**
   * Engine speed over the window: mean and standard deviation, rpm.
   */
  rpm: number;
  /**
   * Engine speed estimated from the recording, without a log.
   */
  rpm_estimated: boolean;
  rpm_spread: number;
  spectrogram: SpectrogramDifference;
  /**
   * The window checked, s from the recording's start (at most 20 s).
   *
   * @minItems 2
   * @maxItems 2
   */
  window_s: [number, number];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "BandComparison".
 */
export interface BandComparison {
  center_hz: number;
  /**
   * Predicted less measured, dB.
   */
  error_db?: number | null;
  /**
   * Measured level, dB re 20 µPa, corrected for the background when one is given; `None`
   * where the recording cannot give it.
   */
  measured_db?: number | null;
  /**
   * Why the measured level is missing or corrected.
   */
  note?: string | null;
  predicted_db?: number | null;
  /**
   * The render resolves this band.
   */
  resolved: boolean;
  /**
   * Indicative target, ± dB (shown, not passed or failed): 3 up to 2 kHz, 5 above.
   */
  target_db: number;
}
/**
 * Predicted less measured level in each ⅓-octave band of each frame (Hann, `frame_s` long,
 * every half frame).
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "SpectrogramDifference".
 */
export interface SpectrogramDifference {
  /**
   * Per frame, per band (`render::third_octaves`), dB; `None` where either level is
   * missing or below the recording's resolution.
   */
  difference_db: (number | null)[][];
  frame_s: number;
  /**
   * Frame centres, s from the window's start.
   */
  times_s: number[];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "RenderInfo".
 */
export interface RenderInfo {
  bands: Band[];
  cells: number;
  cfl: number;
  /**
   * Largest Courant number of any step of the scene.
   */
  cfl_max: number;
  /**
   * Name of each channel.
   */
  channels: string[];
  core_version: string;
  /**
   * Of those, how many take their class's default range.
   */
  default_ranges: number;
  dx_mm: number;
  /**
   * Inputs estimated or derived.
   */
  estimated: number;
  gas_table: string;
  /**
   * Every recorded input with its provenance, source and range.
   */
  inputs: InputUse[];
  /**
   * Equivalent continuous level of each channel, dB re 20 µPa.
   */
  leq_db: number[];
  limiter: Limiter;
  peak_pa: number;
  /**
   * Engine held at the start state before t = 0 so every listener hears it from t = 0, s.
   */
  pre_roll_s: number;
  project_hash: string;
  refinement: Refinement;
  sample_rate: number;
  scene: Scene;
  /**
   * Engine source model and where its EVO states come from.
   */
  source: string;
  start: StartState;
  /**
   * Wall and initial gas temperatures.
   */
  thermal: string;
  warnings: string[];
}
/**
 * One ⅓-octave band (IEC 61260 base-ten centres) and whether the model resolves it.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Band".
 */
export interface Band {
  center_hz: number;
  lower_hz: number;
  /**
   * Why it is not resolved; empty when it is.
   */
  reasons: string[];
  resolved: boolean;
  upper_hz: number;
}
/**
 * A recorded input as a result reports it.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "InputUse".
 */
export interface InputUse {
  /**
   * The range is its class's default, not a stated one.
   */
  default_range: boolean;
  path: string;
  provenance: Provenance2;
  /**
   * The range in force.
   */
  range?: Uncertainty | null;
  source: string;
  /**
   * The value in use.
   */
  value: {
    [k: string]: unknown;
  };
}
/**
 * Where the grid-refinement check ran.
 */
export interface Refinement {
  dx_mm: number;
  fine_dx_mm: number;
  map_kpa: number;
  rpm: number;
}
/**
 * What the render plays: engine speed and load against time, and who hears it.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Scene".
 */
export interface Scene {
  /**
   * Length of the scene, s.
   */
  duration_s: number;
  listener: Listener;
  /**
   * Intake manifold pressure against time, `[[t_s, kPa], …]` (a throttle trace); absent:
   * the project's load line `operating.map_kpa` at the engine speed of the moment.
   */
  map_kpa?: [number, number][] | null;
  /**
   * Engine speed against time, `[[t_s, rpm], …]`, linear between points, held outside.
   */
  rpm: [number, number][];
}
/**
 * The periodic state the scene starts from.
 */
export interface StartState {
  converged: boolean;
  cycles: number;
  map_kpa: number;
  periodicity_residual: number;
  rpm: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Sensitivity".
 */
export interface Sensitivity {
  /**
   * ⅓-octave band centres, Hz.
   */
  bands_hz: number[];
  /**
   * Receiver level with every input as recorded, dB re 20 µPa; `None` above the samples'
   * Nyquist frequency or where nothing sounds.
   */
  base_db: (number | null)[];
  /**
   * Root-sum-square over the inputs of each one's larger change, dB.
   */
  combined_db: (number | null)[];
  /**
   * Inputs on their class's default range first, then by impact.
   */
  inputs: InputEffect[];
  /**
   * Bands above this frequency, Hz, are beyond the model (`render::Limits`); impacts are
   * taken below it.
   */
  limit_hz: number;
  rpm: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "InputEffect".
 */
export interface InputEffect {
  default_range: boolean;
  /**
   * The ends swept: values for a number, scale factors otherwise.
   *
   * @minItems 2
   * @maxItems 2
   */
  ends: [number, number];
  /**
   * Neither end could be built: the input is outside the band.
   */
  error?: string | null;
  high_db: (number | null)[];
  /**
   * Largest change in the resolved bands within 40 dB of the loudest, dB.
   */
  impact_db: number;
  /**
   * Level change at the low and the high end, per band, dB.
   */
  low_db: (number | null)[];
  /**
   * One end could not be built: why, the other end standing for both.
   */
  note?: string | null;
  path: string;
  provenance: Provenance2;
  range: Uncertainty;
  scaled: boolean;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "SweepResult".
 */
export interface SweepResult {
  metrics: Metrics;
  points: PointOutcome[];
  project: string;
  project_hash: string;
  solver: SolverKind;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Metrics".
 */
export interface Metrics {
  /**
   * Exterior, dB.
   */
  boominess_db?: number | null;
  drone_exterior?: DroneReport | null;
  /**
   * Through the measured cabin transfer function; `None` without one.
   */
  drone_interior?: DroneReport | null;
  /**
   * Engine order of firing.
   */
  firing_order: number;
  /**
   * Exterior, dB.
   */
  rasp_proxy_db?: number | null;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "DroneReport".
 */
export interface DroneReport {
  /**
   * Highest level in the cruise band, `[rpm, dB]`; `None` without points in the band.
   *
   * @minItems 2
   * @maxItems 2
   */
  cruise_peak?: [number, number] | null;
  /**
   * Speeds below and above the peak where the track is 3 dB down; `None` where it stays
   * within 3 dB to the end of the sweep.
   *
   * @minItems 2
   * @maxItems 2
   */
  minus_3db_rpm: [number | null, number | null];
  peak_db: number;
  peak_rpm: number;
  /**
   * Firing-order level per solved speed: `[rpm, dB]`.
   */
  track: [number, number][];
  /**
   * Speeds in the track whose time-domain run did not reach periodicity.
   */
  unconverged_rpm: number[];
}
/**
 * Levels of engine orders against engine speed from a recording.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "OrderTracks".
 */
export interface OrderTracks {
  /**
   * Levels in dB re 20 µPa; otherwise dB re full scale.
   */
  calibrated: boolean;
  /**
   * The firing order's drone, as reported for the prediction.
   */
  drone?: DroneReport | null;
  /**
   * Frames analysed and frames within the sweep.
   *
   * @minItems 2
   * @maxItems 2
   */
  frames: [number, number];
  orders: OrderTrack[];
  /**
   * Speed-bin centres (the project's sweep), rpm.
   */
  rpm: number[];
  /**
   * Engine speed estimated from the recording, without a log.
   */
  rpm_estimated: boolean;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "OrderTrack".
 */
export interface OrderTrack {
  /**
   * Per speed bin; `None` where the recording has no frame.
   */
  level_db: (number | null)[];
  order: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Tuning".
 */
export interface Tuning {
  /**
   * The value for the hottest and for the coolest branch gas; absent when the walls are not
   * computed and no temperature is stated.
   *
   * @minItems 2
   * @maxItems 2
   */
  band?: [number, number] | null;
  /**
   * Where the branch gas temperature comes from.
   */
  basis: string;
  /**
   * Mean branch gas temperature at each value (nominal, then hottest and coolest), K.
   */
  branch_temperature_k: number[];
  element: string;
  /**
   * The parameter sized: `length_mm` (stub) or `volume_l` (Helmholtz).
   */
  parameter: string;
  /**
   * The branch's resonance as drawn.
   */
  resonance_hz: number;
  /**
   * Engine speed whose thermal state the branch gas takes.
   */
  rpm: number;
  target_hz: number;
  value: number;
}
/**
 * A case run on demand: its checks, or why it did not run.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "CaseReport".
 */
export interface CaseReport {
  case: string;
  checks: Check[];
  error?: string | null;
  subsystem: string;
}
/**
 * One validated quantity.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Check".
 */
export interface Check {
  case: string;
  /**
   * Pass when `value <= limit`.
   */
  limit: number;
  metric: string;
  pass: boolean;
  value: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Refinement".
 */
export interface Refinement1 {
  dx_mm: number;
  fine_dx_mm: number;
  map_kpa: number;
  rpm: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "StartState".
 */
export interface StartState1 {
  converged: boolean;
  cycles: number;
  map_kpa: number;
  periodicity_residual: number;
  rpm: number;
}
