// Generated by `npm run types` from schemas/; do not edit.

/**
 * A piece of centreline starting `s0_mm` along its route.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PieceLayout".
 */
export type PieceLayout =
  | {
      /**
       * @minItems 3
       * @maxItems 3
       */
      from: [number, number, number];
      kind: "straight";
      s0_mm: number;
      /**
       * @minItems 3
       * @maxItems 3
       */
      to: [number, number, number];
    }
  | {
      angle_deg: number;
      /**
       * @minItems 3
       * @maxItems 3
       */
      centre: [number, number, number];
      /**
       * @minItems 3
       * @maxItems 3
       */
      from: [number, number, number];
      kind: "arc";
      radius_mm: number;
      s0_mm: number;
      /**
       * @minItems 3
       * @maxItems 3
       */
      to: [number, number, number];
    };
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "ParamKind".
 */
export type ParamKind = "number" | "material" | "direction" | "offsets";
/**
 * Where the in-cylinder state at EVO came from.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "EvoSource".
 */
export type EvoSource =
  | {
      kind: "estimated";
      map_kpa: number;
    }
  | {
      kind: "given";
    };
/**
 * Which solver produced a result.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "SolverKind".
 */
export type SolverKind = "time_domain" | "four_pole";
/**
 * TVD slope limiter for MUSCL reconstruction of primitive variables.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Limiter".
 */
export type Limiter = "minmod" | "van_leer" | "van_leer_tvb";
/**
 * A point either solved or failed; failures carry the reason and no numbers.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PointOutcome".
 */
export type PointOutcome =
  | (PointResult & {
      status: "solved";
    })
  | {
      error: string;
      rpm: number;
      status: "failed";
    };

/**
 * The app backend's replies, for generating the frontend's types.
 */
export interface Api {
  layout: Layout;
  manifests: Manifest[];
  /**
   * One operating point as a time-domain sweep streams it.
   */
  point:
    | (PointResult & {
        status: "solved";
      })
    | {
        error: string;
        rpm: number;
        status: "failed";
      };
  sweep: SweepResult;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Layout".
 */
export interface Layout {
  elements: ElementLayout[];
  routes: RouteLayout[];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "ElementLayout".
 */
export interface ElementLayout {
  /**
   * Outer envelope as coaxial frustums (cones and cylinders).
   */
  body: Frustum[];
  id: string;
  ports: PortLayout[];
  type: string;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Frustum".
 */
export interface Frustum {
  d_from_mm: number;
  d_to_mm: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  from: [number, number, number];
  /**
   * @minItems 3
   * @maxItems 3
   */
  to: [number, number, number];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PortLayout".
 */
export interface PortLayout {
  name: string;
  /**
   * @minItems 3
   * @maxItems 3
   */
  position: [number, number, number];
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "RouteLayout".
 */
export interface RouteLayout {
  /**
   * Centreline radius of the bend at each via point.
   */
  bend_radius_mm: number[];
  id: string;
  /**
   * Centreline length: the flow solver's x-axis along this route.
   */
  length_mm: number;
  material: string;
  od_mm: number;
  pieces: PieceLayout[];
  /**
   * Start port, via points, end port.
   */
  points: [number, number, number][];
  wall_mm: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Manifest".
 */
export interface Manifest {
  name: string;
  param?: Param[];
  /**
   * Fixed ports; a chamber adds `out2`, `out3`, … for its extra outlets.
   */
  ports: string[];
  summary: string;
  /**
   * Element type, as in the project file.
   */
  type: string;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Param".
 */
export interface Param {
  default?: number | null;
  /**
   * Field name in the project file.
   */
  key: string;
  kind: ParamKind;
  label: string;
  max?: number | null;
  min?: number | null;
  /**
   * Numbers only: unit, inclusive range, and the editor's default.
   */
  unit?: string | null;
}
/**
 * Solution at one engine speed.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "PointResult".
 */
export interface PointResult {
  /**
   * Mean static pressure above ambient at the downpipe flange, Pa (time domain only).
   */
  backpressure_pa?: number | null;
  /**
   * |outlet mass − source mass| / source mass over the analysed cycles (time domain only).
   */
  mass_balance_error?: number | null;
  mass_flow_kg_s: number;
  /**
   * Engine orders 1–8: `(order, frequency_hz, spl_db)`.
   */
  orders: [number, number, number][];
  /**
   * Mean gas temperature leaving the reference outlet, K.
   */
  outlet_temperature_k: number;
  overall_db: number;
  overall_dba: number;
  provenance: Provenance;
  rpm: number;
  spectrum: Line[];
  turbine_power_w: number;
}
/**
 * How a result was produced; attached to every result.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Provenance".
 */
export interface Provenance {
  cells: number;
  core_version: string;
  dx_max_mm: number;
  dx_min_mm: number;
  dx_target_mm: number;
  evo: EvoState;
  evo_source: EvoSource;
  gas_table: string;
  project_hash: string;
  /**
   * Four-pole result of a network with elements that are nonlinear at exhaust amplitudes
   * (valves, orifices): valid for small signals only.
   */
  small_signal: boolean;
  solver: SolverKind;
  /**
   * Wall and gas temperature model, with a BLAKE3 hash of its inputs.
   */
  thermal_profile: string;
  /**
   * Time-domain run details; absent for four-pole results.
   */
  time_domain?: TimeDomainRun | null;
  /**
   * Modelling limitations that affect this result.
   */
  warnings: string[];
}
/**
 * In-cylinder state at exhaust valve opening.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "EvoState".
 */
export interface EvoState {
  /**
   * Pa.
   */
  pressure_pa: number;
  /**
   * K.
   */
  temperature_k: number;
}
/**
 * Scheme and convergence of a time-domain run.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "TimeDomainRun".
 */
export interface TimeDomainRun {
  cfl: number;
  cfl_max: number;
  converged: boolean;
  cycles: number;
  limiter: Limiter;
  /**
   * Period of the solution in engine cycles (1 or 2).
   */
  period_cycles: number;
  /**
   * Largest relative change of the monitored signals between the last cycle and the cycle
   * one period earlier.
   */
  periodicity_residual: number;
  periodicity_tolerance: number;
}
/**
 * One spectral line at the receiver.
 *
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Line".
 */
export interface Line {
  frequency_hz: number;
  /**
   * Engine order (multiples of ½ for a four-stroke).
   */
  order: number;
  /**
   * Phase of the receiver pressure, rad (`e^{jωt}`, t = 0 at cylinder 1 firing TDC).
   */
  phase_rad: number;
  spl_db: number;
  spl_dba: number;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "SweepResult".
 */
export interface SweepResult {
  metrics: Metrics;
  points: PointOutcome[];
  project: string;
  project_hash: string;
  solver: SolverKind;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "Metrics".
 */
export interface Metrics {
  /**
   * Exterior, dB.
   */
  boominess_db?: number | null;
  drone_exterior?: DroneReport | null;
  /**
   * Through the measured cabin transfer function; `None` without one.
   */
  drone_interior?: DroneReport | null;
  /**
   * Engine order of firing.
   */
  firing_order: number;
  /**
   * Exterior, dB.
   */
  rasp_proxy_db?: number | null;
}
/**
 * This interface was referenced by `Api`'s JSON-Schema
 * via the `definition` "DroneReport".
 */
export interface DroneReport {
  /**
   * Highest level in the cruise band, `[rpm, dB]`; `None` without points in the band.
   *
   * @minItems 2
   * @maxItems 2
   */
  cruise_peak?: [number, number] | null;
  /**
   * Speeds below and above the peak where the track is 3 dB down; `None` where it stays
   * within 3 dB to the end of the sweep.
   *
   * @minItems 2
   * @maxItems 2
   */
  minus_3db_rpm: [number | null, number | null];
  peak_db: number;
  peak_rpm: number;
  /**
   * Firing-order level per solved speed: `[rpm, dB]`.
   */
  track: [number, number][];
  /**
   * Speeds in the track whose time-domain run did not reach periodicity.
   */
  unconverged_rpm: number[];
}
