// Generated by `npm run types` from schemas/; do not edit.

/**
 * Where a value comes from, in order of precedence.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Provenance".
 */
export type Provenance = "measured" | "published" | "derived" | "estimated";
/**
 * How far a value may be from the truth.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Uncertainty".
 */
export type Uncertainty =
  | {
      high: number;
      kind: "range";
      low: number;
    }
  | {
      fraction: number;
      kind: "relative";
    }
  | {
      kind: "absolute";
      plus_minus: number;
    }
  | {
      factor: number;
      kind: "factor";
    };
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "MaterialFamily".
 */
export type MaterialFamily = "ferritic_stainless" | "austenitic_stainless" | "titanium";
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "CabinTfMethod".
 */
export type CabinTfMethod = "order_ratio" | "impulse";
/**
 * Where the microphone was.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "MicPosition".
 */
export type MicPosition = "exterior" | "interior";
/**
 * TVD slope limiter for MUSCL reconstruction of primitive variables.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Limiter".
 */
export type Limiter = "minmod" | "van_leer" | "van_leer_tvb";
/**
 * How the pipe wall exchanges heat with the gas in the time-domain solver.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "WallThermal".
 */
export type WallThermal =
  | {
      model: "adiabatic";
    }
  | {
      model: "fixed";
      temperature_k: number;
    }
  | {
      model: "computed";
    };
/**
 * Element types and their parameters. Port names are fixed per type (see
 * [`ElementKind::port_names`]); pipes attach to ports by name.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Element".
 */
export type Element = {
  /**
   * Flow direction through the element (normalised on use).
   *
   * @minItems 3
   * @maxItems 3
   */
  axis?: [number, number, number];
  id: string;
  /**
   * Position of the element's first port, mm.
   *
   * @minItems 3
   * @maxItems 3
   */
  position_mm: [number, number, number];
} & Element1;
export type Element1 =
  | {
      type: "source";
    }
  | {
      type: "outlet";
    }
  | {
      taper_length_mm: number;
      type: "area_change";
    }
  | {
      type: "cap";
    }
  | {
      /**
       * Inner diameter of the shell, mm.
       */
      diameter_mm: number;
      extra_outlets_mm?: [number, number, number][];
      inlet_extension_mm?: number;
      length_mm: number;
      outlet_extension_mm?: number;
      /**
       * Shell thickness, mm (heat loss and fabrication).
       */
      shell_mm?: number;
      type: "expansion_chamber";
    }
  | {
      /**
       * @minItems 3
       * @maxItems 3
       */
      direction?: [number, number, number];
      id_mm: number;
      /**
       * Physical length from the main-pipe wall to the cap, mm.
       */
      length_mm: number;
      material: string;
      type: "quarter_wave_stub";
      wall_mm: number;
    }
  | {
      cavity_diameter_mm: number;
      /**
       * @minItems 3
       * @maxItems 3
       */
      direction?: [number, number, number];
      neck_id_mm: number;
      /**
       * Physical neck length, mm.
       */
      neck_length_mm: number;
      type: "helmholtz";
      volume_l: number;
    }
  | {
      brick_diameter_mm: number;
      brick_length_mm: number;
      /**
       * Cell wall thickness, mm (4 mil = 0.1016 mm).
       */
      cell_wall_mm: number;
      /**
       * Cells per square inch.
       */
      cpsi: number;
      inlet_cone_mm?: number;
      outlet_cone_mm?: number;
      type: "catalyst";
    }
  | {
      /**
       * Disc opening: 0° closed, 90° fully open.
       */
      angle_deg: number;
      type: "valve";
    }
  | {
      /**
       * @minItems 3
       * @maxItems 3
       */
      branch_direction?: [number, number, number];
      type: "tee";
    }
  | {
      /**
       * Inner diameter of the case, mm.
       */
      case_diameter_mm: number;
      /**
       * Fibre diameter, µm (basalt or glass wool ≈ 10–13 µm).
       */
      fiber_diameter_um?: number;
      /**
       * Packing density, kg/m³ (0: empty annulus).
       */
      fill_density_kg_m3?: number;
      hole_diameter_mm: number;
      length_mm: number;
      /**
       * Open-area ratio of the perforated tube.
       */
      open_area_ratio: number;
      /**
       * Perforated tube wall, mm.
       */
      perforate_thickness_mm: number;
      shell_mm?: number;
      type: "absorptive";
    };
/**
 * How two parts are joined.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Joint".
 */
export type Joint = "butt" | "slip" | "v_band" | "flange";

export interface Project {
  ambient: Ambient;
  engine: EngineSpec;
  fabrication?: Fabrication & {
    [k: string]: unknown;
  };
  gas: GasSpec;
  /**
   * Provenance, source and range of recorded inputs, keyed by dotted field path (e.g.
   * `engine.geometry.bore_mm`, or `system.elements.cat` for a whole element; `inputs`).
   * Unrecorded values are the user's own entries.
   */
  inputs?: {
    [k: string]: Input;
  };
  materials: Material[];
  measurements?: Measurements;
  name: string;
  notes?: string;
  operating: Operating;
  receiver: Receiver;
  schema_version: number;
  solver: SolverSettings;
  system: System;
  turbine: TurbineSpec;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Ambient".
 */
export interface Ambient {
  /**
   * Height of the ground plane in vehicle coordinates, mm (negative: below the flange).
   */
  ground_z_mm: number;
  pressure_pa: number;
  temperature_k: number;
  /**
   * Air speed across the pipes as a fraction of vehicle speed (underbody boundary layer).
   */
  underbody_air_factor?: number;
  /**
   * Vehicle speed; sets the external film coefficient in the thermal model.
   */
  vehicle_speed_kmh: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "EngineSpec".
 */
export interface EngineSpec {
  geometry: EngineGeometry;
  label: string;
  /**
   * Polytropic exponent of the cylinder gas after EVO.
   */
  polytropic_exponent: number;
  valves: ExhaustValves;
}
/**
 * Slider-crank geometry and firing order.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "EngineGeometry".
 */
export interface EngineGeometry {
  /**
   * Bore, mm.
   */
  bore_mm: number;
  /**
   * Geometric compression ratio.
   */
  compression_ratio: number;
  /**
   * Firing order, 1-based cylinder numbers. Four-stroke: cylinders fire at equal intervals
   * of 720°/n.
   */
  firing_order: number[];
  /**
   * Connecting-rod centre distance, mm.
   */
  rod_mm: number;
  /**
   * Stroke, mm.
   */
  stroke_mm: number;
}
/**
 * Exhaust valve train of one cylinder.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ExhaustValves".
 */
export interface ExhaustValves {
  /**
   * Discharge coefficient referred to the geometric flow area.
   */
  discharge_coefficient: number;
  /**
   * Exhaust valve closing, crank degrees after firing TDC (e.g. 370 = 10° after gas-exchange TDC).
   */
  evc_deg: number;
  /**
   * Exhaust valve opening, crank degrees after firing TDC.
   */
  evo_deg: number;
  /**
   * Measured lift curve: (crank degrees after firing TDC, lift mm), linearly interpolated.
   */
  lift_table?: [number, number][] | null;
  /**
   * Peak lift, mm, of the raised-cosine profile `L = L_max (1 − cos 2πφ)/2`,
   * `φ = (θ − EVO)/(EVC − EVO)`. Ignored when `lift_table` is given.
   */
  max_lift_mm: number;
  /**
   * Port throat (inner seat) diameter, mm; caps the flow area at π d²/4 per valve.
   */
  throat_diameter_mm: number;
  /**
   * Valve head diameter, mm (curtain area π d L).
   */
  valve_diameter_mm: number;
  valves_per_cylinder: number;
}
/**
 * Fabrication settings: stock, cutting, and underbody clearance.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Fabrication".
 */
export interface Fabrication {
  /**
   * Gap wanted between pipe surface and underbody, mm.
   */
  clearance_mm?: number;
  /**
   * Stretches that need a different gap (near the rear axle, say).
   */
  clearance_zones?: ClearanceZone[];
  /**
   * Saw kerf per cut, mm.
   */
  kerf_mm?: number;
  /**
   * Underbody scan and where it sits on the car.
   */
  scan?: Scan | null;
  /**
   * A stock 45° or 90° mandrel bend is used uncut within this angle, degrees.
   */
  stock_bend_tolerance_deg?: number;
  /**
   * Straight tube is bought in lengths of, mm (10 ft).
   */
  stock_length_mm?: number;
}
/**
 * A stretch along the car, `x_min_mm ≤ x ≤ x_max_mm`, with its own clearance.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ClearanceZone".
 */
export interface ClearanceZone {
  clearance_mm: number;
  name: string;
  x_max_mm: number;
  x_min_mm: number;
}
/**
 * An underbody scan (STL or OBJ, metres or millimetres as `unit_mm` says) and three points on
 * it with their places on the car (jack pads, say), which fix its position.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Scan".
 */
export interface Scan {
  /**
   * Relative to the project file, or absolute.
   */
  path: string;
  /**
   * Reference points in scan coordinates (scan units).
   *
   * @minItems 3
   * @maxItems 3
   */
  scan_points: [[number, number, number], [number, number, number], [number, number, number]];
  /**
   * Millimetres per scan unit (1000 for a scan in metres).
   */
  unit_mm?: number;
  /**
   * The same points in vehicle coordinates, mm.
   *
   * @minItems 3
   * @maxItems 3
   */
  vehicle_points_mm: [[number, number, number], [number, number, number], [number, number, number]];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "GasSpec".
 */
export interface GasSpec {
  /**
   * Fuel hydrogen-to-carbon atom ratio (gasoline ≈ 1.87).
   */
  fuel_h_to_c: number;
  /**
   * Air-excess ratio λ (≥ 1).
   */
  lambda: number;
}
/**
 * The recorded origin of one input.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Input".
 */
export interface Input {
  /**
   * Values this input has had from other sources.
   */
  alternatives?: Alternative[];
  /**
   * The user chose the value in the field over alternatives of higher precedence.
   */
  chosen?: boolean;
  /**
   * Where a value comes from, in order of precedence.
   */
  provenance: "measured" | "published" | "derived" | "estimated";
  /**
   * File, citation, or estimation method.
   */
  source: string;
  /**
   * Stated range; absent: the default range of the input's class.
   */
  uncertainty?: Uncertainty | null;
}
/**
 * A value an input has had from another source.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Alternative".
 */
export interface Alternative {
  provenance: Provenance;
  source: string;
  uncertainty?: Uncertainty | null;
  /**
   * The field's value from this source, in the field's own form.
   */
  value: {
    [k: string]: unknown;
  };
}
/**
 * Tube material.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Material".
 */
export interface Material {
  conductivity_w_mk: number;
  density_kg_m3: number;
  /**
   * Total hemispherical emissivity of the oxidised outer surface.
   */
  emissivity: number;
  family: MaterialFamily;
  id: string;
  name: string;
}
/**
 * Data measured on the vehicle and stored with the project.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Measurements".
 */
export interface Measurements {
  /**
   * Without it the interior drone is unavailable: the cabin is never synthesised.
   */
  cabin_tf?: CabinTf | null;
  /**
   * Recordings of the car to set against the prediction.
   */
  recordings?: RecordingRef[];
}
/**
 * Cabin transfer function: level at the driver's ear minus level at the exterior receiver.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "CabinTf".
 */
export interface CabinTf {
  /**
   * `[[frequency_hz, gain_db], …]`, frequency increasing; linear between points, undefined
   * outside them.
   */
  gain_db: [number, number][];
  method: CabinTfMethod;
  /**
   * Where and when it was measured.
   */
  source: string;
}
/**
 * A recording of the car (WAV or CAF) and the engine-speed log taken with it.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "RecordingRef".
 */
export interface RecordingRef {
  /**
   * Sound pressure level of a full-scale sine, dB re 20 µPa; without it levels are dB re
   * full scale.
   */
  calibration_db?: number | null;
  /**
   * Time on the log (from its first row) at the start of the recording, s.
   */
  log_offset_s?: number;
  /**
   * Relative to the project file, or absolute.
   */
  path: string;
  position: MicPosition;
  /**
   * CSV of engine speed against time from an OBD logger, as `path`; without one the
   * engine speed is estimated from the recording and flagged.
   */
  rpm_log?: string | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Operating".
 */
export interface Operating {
  /**
   * Engine-speed band searched for drone, rpm.
   *
   * @minItems 2
   * @maxItems 2
   */
  cruise_band_rpm: [number, number];
  /**
   * Measured in-cylinder state at EVO; replaces the Otto-cycle estimate when present.
   */
  evo_override?: EvoState | null;
  /**
   * Fraction of fuel heating value in the cylinder gas after combustion and wall losses.
   */
  heat_retained: number;
  intake_temperature_k: number;
  lhv_mj_per_kg: number;
  /**
   * Intake manifold absolute pressure against engine speed: `[[rpm, kPa], …]`, linear,
   * held constant outside the table.
   */
  map_kpa: [number, number][];
  n_compression: number;
  n_expansion: number;
  /**
   * Default sweep: `[start, stop, step]`, rpm.
   *
   * @minItems 3
   * @maxItems 3
   */
  sweep_rpm: [number, number, number];
  volumetric_efficiency: number;
}
/**
 * In-cylinder state at exhaust valve opening.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "EvoState".
 */
export interface EvoState {
  /**
   * Pa.
   */
  pressure_pa: number;
  /**
   * K.
   */
  temperature_k: number;
}
/**
 * Microphone position (ISO 5130 by default: 0.5 m from the outlet, 45° to its axis,
 * outlet height, on the outboard side).
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Receiver".
 */
export interface Receiver {
  angle_deg: number;
  distance_m: number;
  /**
   * Reference outlet element id; the first outlet when absent.
   */
  outlet?: string | null;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "SolverSettings".
 */
export interface SolverSettings {
  /**
   * Courant number, ≤ 0.8.
   */
  cfl: number;
  /**
   * Target cell length, mm (10–20 mm baseline).
   */
  dx_mm: number;
  friction: boolean;
  limiter: Limiter;
  max_cycles: number;
  max_frequency_hz: number;
  min_cycles: number;
  /**
   * Converged when the last cycle differs from the one before by less than this fraction
   * (RMS of the difference over RMS of the fluctuation) in every monitored signal.
   */
  periodicity_tolerance: number;
  /**
   * Output samples per engine cycle (power of two).
   */
  samples_per_cycle: number;
  wall_roughness_mm: number;
  wall_thermal: WallThermal;
}
/**
 * Exhaust system graph.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "System".
 */
export interface System {
  elements: Element[];
  routes: Route[];
}
/**
 * A bent tube between two ports.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "Route".
 */
export interface Route {
  /**
   * Centreline bend radius at each interior vertex, mm; `null` uses 1.5 × OD.
   */
  bend_radius_mm?: (number | null)[];
  /**
   * Joint to the element at the route's end; absent as for `start_joint`.
   */
  end_joint?: Joint | null;
  from: PortRef;
  /**
   * Hangers, mm along the centreline from the route's start.
   */
  hangers_mm?: number[];
  id: string;
  pipe: PipeSpec;
  /**
   * Joint to the element at the route's start; absent: a flange at the source, else a
   * butt weld.
   */
  start_joint?: Joint | null;
  to: PortRef;
  /**
   * Interior centreline vertices, mm; the ends are the ports' positions.
   */
  via_mm?: [number, number, number][];
}
/**
 * A port on an element.
 *
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "PortRef".
 */
export interface PortRef {
  element: string;
  port: string;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "PipeSpec".
 */
export interface PipeSpec {
  /**
   * Material id from `materials`.
   */
  material: string;
  od_mm: number;
  wall_mm: number;
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "TurbineSpec".
 */
export interface TurbineSpec {
  /**
   * Temperature the ports and housing reject heat to, K.
   */
  coolant_temperature_k?: number;
  /**
   * Fraction of the isentropic enthalpy drop across the turbine removed as shaft work.
   */
  extraction_factor: number;
  scrolls: ScrollSpec[];
}
/**
 * This interface was referenced by `Project`'s JSON-Schema
 * via the `definition` "ScrollSpec".
 */
export interface ScrollSpec {
  /**
   * 1-based cylinders feeding this scroll.
   */
  cylinders: number[];
  /**
   * Heat-loss conductance of ports, runners and turbine housing to the coolant, W/K.
   */
  heat_loss_w_per_k?: number;
  /**
   * Volume of exhaust ports, manifold runners and scroll, litres.
   */
  manifold_volume_l: number;
  /**
   * Effective nozzle area `C_d A` of the scroll including an open wastegate, cm².
   */
  nozzle_area_cm2: number;
}
