// Generates the frontend's types from the checked-in schemas, which the Rust types generate
// (`UPDATE_SCHEMA=1 cargo test -p exhaust-core --test schema`). Run from app/.
import { readFileSync, writeFileSync } from 'node:fs';
import { compile } from 'json-schema-to-typescript';

// The generator predates two JSON Schema 2020-12 forms schemars emits: `$ref` beside other
// keywords (a tagged enum variant) becomes `allOf`, and `prefixItems` (a tuple) draft-07 `items`.
function normalize(node) {
  if (Array.isArray(node)) return node.map(normalize);
  if (!node || typeof node !== 'object') return node;
  const out = Object.fromEntries(Object.entries(node).map(([k, v]) => [k, normalize(v)]));
  if (out.$ref && Object.keys(out).some((k) => k !== '$ref' && k !== 'description')) {
    const { $ref, description, ...rest } = out;
    return { ...(description ? { description } : {}), allOf: [{ $ref }, rest] };
  }
  if (out.prefixItems) {
    const { prefixItems, ...rest } = out;
    const n = prefixItems.length;
    return { ...rest, items: prefixItems, minItems: n, maxItems: n };
  }
  return out;
}

const banner = '// Generated by `npm run types` from schemas/; do not edit.\n';
for (const [schema, name, out] of [
  ['../schemas/project.schema.json', 'Project', 'src/lib/types/project.ts'],
  ['../schemas/api.schema.json', 'Api', 'src/lib/types/api.ts'],
]) {
  const ts = await compile(normalize(JSON.parse(readFileSync(schema, 'utf8'))), name, {
    bannerComment: banner,
    unreachableDefinitions: true,
    additionalProperties: false,
  });
  writeFileSync(out, ts);
}
